jobs:
- name: simple-job
  build_logs_to_retain: 20
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args: ["Hello, world!"]
- name: failing
  build_logs_to_retain: 20
  plan:
  - task: fail
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: false
